[project]
name = "desktop-detection-v3"
version = "0.3.0"
requires-python = ">=3.11"
dependencies = [
    "torch",
    "torchvision",
    "ultralytics>=8.4.123",
]

[tool.uv.sources]
torch = { index = "pytorch-cu126" }
torchvision = { index = "pytorch-cu126" }

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
